[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    ui: triggers all ui auto-tests
    smoke:  triggers all smoke auto-tests
    regression:  triggers all regression auto-tests
    slow:  triggers all slow auto-tests
    registration:  triggers all registration auto-tests
    critical:  triggers all critical auto-tests
    authorisation: triggers all authorisation auto-tests