name : UI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

# Шаг 1: Чистый скрипт на Python, который создаёт файл состояния в один поток
      - name: Pre-generate browser state
        run: |
          python -c "
          from playwright.sync_api import sync_playwright
          import os
          os.makedirs('tools/playwright', exist_ok=True)
          with sync_playwright() as p:
              browser = p.chromium.launch(headless=True)
              context = browser.new_context()
              page = context.new_page()
              page.goto('https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/auth/registration')
              page.locator('input[type=\"email\"]').fill('grigoriishneer88@gmail.com')
              page.locator('input[type=\"password\"]').fill('твоя_пароль_из_settings')
              page.locator('input[placeholder=\"Name\"]').fill('Gregory')
              page.locator('button', has_text='Зарегистрироваться').click()
              page.wait_for_load_state('networkidle')
              context.storage_state(path='tools/playwright/storage_state.json')
              context.close()
              browser.close()
          print('Storage state file successfully generated!')"

      # Шаг 2: Спокойно запускаем все тесты параллельно
      - name: Run remaining tests in parallel
        run: xvfb-run pytest -m regression --alluredir=./allure-results --numprocesses=2

      - name: Load Allure History from GitHub Pages
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install Allure CLI and Generate Report
        if: always()
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          sudo tar -zxvf allure-2.24.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.0/bin/allure /usr/bin/allure
          
          if [ -d "gh-pages-dir/history" ]; then
            cp -r gh-pages-dir/history ./allure-results/
          fi
          
          allure generate ./allure-results --clean -o ./allure-history

      - name: Deploy on GitHub pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history